application: mino-pausa-bot
version: 1-1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: setuptools
  version: "0.6c11"
- name: lxml
  version: "2.3"
- name: ssl
  version: "2.7"
